# Generated by Django 6.0.3 on 2026-05-29 10:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test_body',
            field=wagtail.fields.StreamField([('hero_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This will be the background image of a block', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a header text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('header_text', 1)]], {})}, null=True),
        ),
    ]
