# Generated by Django 6.0.3 on 2026-06-06 04:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_test_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='test_body',
            field=wagtail.fields.StreamField([('hero_block', 2), ('highlights_block', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This will be the background image of a block', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a header text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('header_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title text', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Highlight title', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Highlight body', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('body', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add at least three highlights (each with a title and body)', 'min_num': 3}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('highlights', 7)]], {})}, null=True),
        ),
    ]
