# Generated by Django 6.0.3 on 2026-06-06 05:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_test_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='test_body',
            field=wagtail.fields.StreamField([('hero_block', 2), ('highlights_block', 8), ('about_block', 14), ('call_to_action_block', 18)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This will be the background image of a block', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a header text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('header_text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title text', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Highlight title', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Highlight body', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('body', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add at least three highlights (each with a title and body)', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('highlights', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title for the about block', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the subtitle for the about block', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a listed feature', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('text', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Add the features of this project'}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('subtitle', 10), ('features', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title for the call to action block', 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the subtitle for the call to action block', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the name for the call to action button', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('title', 15), ('subtitle', 16), ('button_name', 17)]], {})}, null=True),
        ),
    ]
