# Generated by Django 6.0.3 on 2026-06-06 05:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_test_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='test_body',
            field=wagtail.fields.StreamField([('home_title_block', 1), ('hero_block', 4), ('highlights_block', 10), ('about_block', 16), ('call_to_action_block', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title for the home page', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('title', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This will be the background image of a block', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a header text', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 2), ('header_text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title text', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Highlight title', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Highlight body', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('body', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Add at least three highlights (each with a title and body)', 'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('highlights', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title for the about block', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the subtitle for the about block', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is a listed feature', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Add the features of this project'}), 16: ('wagtail.blocks.StructBlock', [[('title', 11), ('subtitle', 12), ('features', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the title for the call to action block', 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the subtitle for the call to action block', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is the name for the call to action button', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('subtitle', 18), ('button_name', 19)]], {})}, null=True),
        ),
    ]
